# Generated by Django 3.2.8 on 2021-10-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_dog_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='Owner',
            new_name='owner',
        ),
    ]
